package com.fruit.manage.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProductMarket<M extends BaseProductMarket<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return getInt("id");
	}

	public void setProductId(Integer productId) {
		set("product_id", productId);
	}

	public Integer getProductId() {
		return getInt("product_id");
	}

	public void setBuySuggest(String buySuggest) {
		set("buy_suggest", buySuggest);
	}

	public String getBuySuggest() {
		return getStr("buy_suggest");
	}

	public void setMarketFeedback(Integer marketFeedback) {
		set("market_feedback", marketFeedback);
	}

	public Integer getMarketFeedback() {
		return getInt("market_feedback");
	}

	public void setSupplyGoods(Integer supplyGoods) {
		set("supply_goods", supplyGoods);
	}

	public Integer getSupplyGoods() {
		return getInt("supply_goods");
	}

	public void setFruitDes(String fruitDes) {
		set("fruit_des", fruitDes);
	}

	public String getFruitDes() {
		return getStr("fruit_des");
	}

	public void setSupportDes(String supportDes) {
		set("support_des", supportDes);
	}

	public String getSupportDes() {
		return getStr("support_des");
	}

	public void setRemark(String remark) {
		set("remark", remark);
	}

	public String getRemark() {
		return getStr("remark");
	}

	public void setLastEditUserId(Integer lastEditUserId) {
		set("last_edit_user_id", lastEditUserId);
	}

	public Integer getLastEditUserId() {
		return getInt("last_edit_user_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
