package com.fruit.manage.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProduct<M extends BaseProduct<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return getInt("id");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return getStr("name");
	}

	public void setFruitType(String fruitType) {
		set("fruit_type", fruitType);
	}

	public String getFruitType() {
		return getStr("fruit_type");
	}

	public void setCountry(String country) {
		set("country", country);
	}

	public String getCountry() {
		return getStr("country");
	}

	public void setProvince(String province) {
		set("province", province);
	}

	public String getProvince() {
		return getStr("province");
	}

	public void setSort(Long sort) {
		set("sort", sort);
	}

	public Long getSort() {
		return getLong("sort");
	}

	public void setBrand(String brand) {
		set("brand", brand);
	}

	public String getBrand() {
		return getStr("brand");
	}

	public void setMeasureUnit(String measureUnit) {
		set("measure_unit", measureUnit);
	}

	public String getMeasureUnit() {
		return getStr("measure_unit");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}

	public Integer getStatus() {
		return getInt("status");
	}

	public void setFreshTime(Integer freshTime) {
		set("fresh_time", freshTime);
	}

	public Integer getFreshTime() {
		return getInt("fresh_time");
	}

	public void setFreshExpireTime(java.util.Date freshExpireTime) {
		set("fresh_expire_time", freshExpireTime);
	}

	public java.util.Date getFreshExpireTime() {
		return get("fresh_expire_time");
	}

	public void setImg(String img) {
		set("img", img);
	}

	public String getImg() {
		return getStr("img");
	}

	public void setFruitDes(String fruitDes) {
		set("fruit_des", fruitDes);
	}

	public String getFruitDes() {
		return getStr("fruit_des");
	}

	public void setStoreWay(String storeWay) {
		set("store_way", storeWay);
	}

	public String getStoreWay() {
		return getStr("store_way");
	}

	public void setTotalSellNum(Integer totalSellNum) {
		set("total_sell_num", totalSellNum);
	}

	public Integer getTotalSellNum() {
		return getInt("total_sell_num");
	}

	public void setWeekSellNum(Integer weekSellNum) {
		set("week_sell_num", weekSellNum);
	}

	public Integer getWeekSellNum() {
		return getInt("week_sell_num");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
