package com.fruit.manage.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrder<M extends BaseOrder<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return getInt("id");
	}

	public void setOrderId(String orderId) {
		set("order_id", orderId);
	}

	public String getOrderId() {
		return getStr("order_id");
	}

	public void setOrderTime(java.util.Date orderTime) {
		set("order_time", orderTime);
	}

	public java.util.Date getOrderTime() {
		return get("order_time");
	}

	public void setModifyTime(java.util.Date modifyTime) {
		set("modify_time", modifyTime);
	}

	public java.util.Date getModifyTime() {
		return get("modify_time");
	}

	public void setOrderStatus(Integer orderStatus) {
		set("order_status", orderStatus);
	}

	public Integer getOrderStatus() {
		return getInt("order_status");
	}

	public void setOrderFinishTime(java.util.Date orderFinishTime) {
		set("order_finish_time", orderFinishTime);
	}

	public java.util.Date getOrderFinishTime() {
		return get("order_finish_time");
	}

	public void setOrderAmount(java.math.BigDecimal orderAmount) {
		set("order_amount", orderAmount);
	}

	public java.math.BigDecimal getOrderAmount() {
		return get("order_amount");
	}

	public void setOrderPayAmount(java.math.BigDecimal orderPayAmount) {
		set("order_pay_amount", orderPayAmount);
	}

	public java.math.BigDecimal getOrderPayAmount() {
		return get("order_pay_amount");
	}

	public void setOrderIspay(Integer orderIspay) {
		set("order_ispay", orderIspay);
	}

	public Integer getOrderIspay() {
		return getInt("order_ispay");
	}

	public void setOrderIsrefund(Integer orderIsrefund) {
		set("order_isrefund", orderIsrefund);
	}

	public Integer getOrderIsrefund() {
		return getInt("order_isrefund");
	}

	public void setOrderPaySuccessTime(java.util.Date orderPaySuccessTime) {
		set("order_pay_success_time", orderPaySuccessTime);
	}

	public java.util.Date getOrderPaySuccessTime() {
		return get("order_pay_success_time");
	}

	public void setRemark(String remark) {
		set("remark", remark);
	}

	public String getRemark() {
		return getStr("remark");
	}

	public void setBuyuserUid(Integer buyuserUid) {
		set("buyuser_uid", buyuserUid);
	}

	public Integer getBuyuserUid() {
		return getInt("buyuser_uid");
	}

	public void setConsigneePhone(String consigneePhone) {
		set("consignee_phone", consigneePhone);
	}

	public String getConsigneePhone() {
		return getStr("consignee_phone");
	}

	public void setConsignee(String consignee) {
		set("consignee", consignee);
	}

	public String getConsignee() {
		return getStr("consignee");
	}

	public void setConsigneeAddress(String consigneeAddress) {
		set("consignee_address", consigneeAddress);
	}

	public String getConsigneeAddress() {
		return getStr("consignee_address");
	}

	public void setDeliveryTime(java.util.Date deliveryTime) {
		set("delivery_time", deliveryTime);
	}

	public java.util.Date getDeliveryTime() {
		return get("delivery_time");
	}

	public void setDeliveryType(Integer deliveryType) {
		set("delivery_type", deliveryType);
	}

	public Integer getDeliveryType() {
		return getInt("delivery_type");
	}

	public void setSendProductTime(java.util.Date sendProductTime) {
		set("send_product_time", sendProductTime);
	}

	public java.util.Date getSendProductTime() {
		return get("send_product_time");
	}

	public void setGetProductTime(java.util.Date getProductTime) {
		set("get_product_time", getProductTime);
	}

	public java.util.Date getGetProductTime() {
		return get("get_product_time");
	}

	public void setRefundTime(java.util.Date refundTime) {
		set("refund_time", refundTime);
	}

	public java.util.Date getRefundTime() {
		return get("refund_time");
	}

	public void setRefundAmount(java.math.BigDecimal refundAmount) {
		set("refund_amount", refundAmount);
	}

	public java.math.BigDecimal getRefundAmount() {
		return get("refund_amount");
	}

	public void setCancelTime(java.util.Date cancelTime) {
		set("cancel_time", cancelTime);
	}

	public java.util.Date getCancelTime() {
		return get("cancel_time");
	}

	public void setCancelReason(String cancelReason) {
		set("cancel_reason", cancelReason);
	}

	public String getCancelReason() {
		return getStr("cancel_reason");
	}

	public void setPayFailMsg(String payFailMsg) {
		set("pay_fail_msg", payFailMsg);
	}

	public String getPayFailMsg() {
		return getStr("pay_fail_msg");
	}

	public void setProductId(String productId) {
		set("product_id", productId);
	}

	public String getProductId() {
		return getStr("product_id");
	}

	public void setProductName(String productName) {
		set("product_name", productName);
	}

	public String getProductName() {
		return getStr("product_name");
	}

	public void setProductSinglePrice(java.math.BigDecimal productSinglePrice) {
		set("product_single_price", productSinglePrice);
	}

	public java.math.BigDecimal getProductSinglePrice() {
		return get("product_single_price");
	}

	public void setProductSingleNumber(Long productSingleNumber) {
		set("product_single_number", productSingleNumber);
	}

	public Long getProductSingleNumber() {
		return getLong("product_single_number");
	}

	public void setProductOriginalPrice(java.math.BigDecimal productOriginalPrice) {
		set("product_original_price", productOriginalPrice);
	}

	public java.math.BigDecimal getProductOriginalPrice() {
		return get("product_original_price");
	}

	public void setProductCount(Integer productCount) {
		set("product_count", productCount);
	}

	public Integer getProductCount() {
		return getInt("product_count");
	}

	public void setProductRemark(String productRemark) {
		set("product_remark", productRemark);
	}

	public String getProductRemark() {
		return getStr("product_remark");
	}

	public void setProductOnsaleTime(java.util.Date productOnsaleTime) {
		set("product_onsale_time", productOnsaleTime);
	}

	public java.util.Date getProductOnsaleTime() {
		return get("product_onsale_time");
	}

	public void setProductPosition(Integer productPosition) {
		set("product_position", productPosition);
	}

	public Integer getProductPosition() {
		return getInt("product_position");
	}

	public void setZhifuPlatformWayId(Integer zhifuPlatformWayId) {
		set("zhifu_platform_way_id", zhifuPlatformWayId);
	}

	public Integer getZhifuPlatformWayId() {
		return getInt("zhifu_platform_way_id");
	}

	public void setZhifuPlatformWayName(String zhifuPlatformWayName) {
		set("zhifu_platform_way_name", zhifuPlatformWayName);
	}

	public String getZhifuPlatformWayName() {
		return getStr("zhifu_platform_way_name");
	}

	public void setZhifuStrategyId(Integer zhifuStrategyId) {
		set("zhifu_strategy_id", zhifuStrategyId);
	}

	public Integer getZhifuStrategyId() {
		return getInt("zhifu_strategy_id");
	}

	public void setOrderIp(String orderIp) {
		set("order_ip", orderIp);
	}

	public String getOrderIp() {
		return getStr("order_ip");
	}

}
