package com.fruit.manage.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return getInt("id");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return getStr("name");
	}

	public void setNickName(String nickName) {
		set("nick_name", nickName);
	}

	public String getNickName() {
		return getStr("nick_name");
	}

	public void setPass(String pass) {
		set("pass", pass);
	}

	public String getPass() {
		return getStr("pass");
	}

	public void setPhone(String phone) {
		set("phone", phone);
	}

	public String getPhone() {
		return getStr("phone");
	}

	public void setWeixinToken(String weixinToken) {
		set("weixin_token", weixinToken);
	}

	public String getWeixinToken() {
		return getStr("weixin_token");
	}

	public void setLastLoginTime(java.util.Date lastLoginTime) {
		set("last_login_time", lastLoginTime);
	}

	public java.util.Date getLastLoginTime() {
		return get("last_login_time");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
