package com.fruit.manage.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePermission<M extends BasePermission<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return getInt("id");
	}

	public void setPermissionKey(String permissionKey) {
		set("permission_key", permissionKey);
	}

	public String getPermissionKey() {
		return getStr("permission_key");
	}

	public void setPermissionName(String permissionName) {
		set("permission_name", permissionName);
	}

	public String getPermissionName() {
		return getStr("permission_name");
	}

	public void setDescribe(String describe) {
		set("describe", describe);
	}

	public String getDescribe() {
		return getStr("describe");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
